rust-ammonia/ammonia

- src/lib.rs
Closes #7, though that issue has actually been fixed ever
since switching to html5ever-built-in serialization.
> Test for quotes in attributes

- src/lib.rs
If we leave an empty namespace, html5ever closes void elements.
Fixes #19
> Use the html namespace in the parse_fragment call

- Cargo.toml
- README.md
- benchmarks/Cargo.toml
Since html5ever and tendril dropped their unstable feature, I also
removed our unstable feature as it is now useless.
> Bump dependencies

- CHANGELOG.md
- Cargo.toml
Changelog:
* Resolve relative URLs with a given base (off by default, you need to specify that base URL)
* Add `rel="noreferrer noopener"` to links, as a security measure
* Avoid closing void tags, such as turning `<br>` into `<br></br>`
* Bump the html5ever version
* Switch to using docs.rs to host docs
> Release a new version

- src/lib.rs
From the XSS Filter Evasion Cheat Sheet.
> Add a test case for HTML-entity-ful JS links

- src/lib.rs
Unlike Bleach, the library I originally had in mind, Ammonia does not sanitize "user input with some HTML." It sanitizes HTML. Ammonia is intended to be compliant with the HTML5 standard for parsing and serializing.
If you want to handle "user input with some HTML," run it through a pre-processor first.
> Adjust the crates docs to match the new pitch

- CHANGELOG.md
- src/lib.rs
`keep_cleaned_elements` was added by users who were dissatisfied by how Ammonia behaved differently than other sanitizers (particularly the one used by GitHub). In practice, it seems like everybody turns it on, or doesn't care.
So, why do we have the other option again?
> Always keep cleaned elements

- .travis.yml
- Cargo.toml
- tests/version-numbers.rs
This PR adds an integration tests that uses my [version-sync][1] crate to detect if the version number in the `html_root_url` is ever out of sync with the crate version.
I hope you find this useful :-) It'll also check if TOML code in `README.md` mentions `ammonia` and uses an outdated version number.
[1]: https://crates.io/crates/version-sync
> Ensure that version numbers are in sync with crate version

- src/lib.rs
We may want to keep `id`s from an untrusted source. One way to do this without worrying about name collisions is to prefix the IDs with some known string, effectively namespacing it. (e.g. we do this with anchor IDs at GitHub, prepending `"user-content-"`.)
This spike came up while thinking of solutions to https://github.com/rust-lang/crates.io/issues/1037, where we're trying to get anchor visiting working on crates.io. Currently we generate anchors from Markdown with the prefix, but if we were to allow those through at the sanitization stage, anchors directly entered by users as inline HTML still need to be made safe.
> Add id_prefix

- CHANGELOG.md
- src/lib.rs
This also makes the url crate a public dependency, which should be fine since it's past 1.0 and re-exported here.
Fixes #68
> Make `UrlRelative::RewriteWithBase` take a `Url` instead of a `str`

- src/lib.rs
This doc comment suggests the PR title is already true:
https://github.com/notriddle/ammonia/blob/2a7ee33ce4897343907076a5bd6aeb149b93785e/src/lib.rs#L1290
The attached test case demonstrates otherwise. Will have a fix in this PR momentarily.
> UrlRelative::Custom should only apply to relative URLs

- src/lib.rs
I haven't been able to write some code that didn't compile before, but the lifetime there doesn't look right.
> Drop src lifetime from Builder::clean

- README.md
- src/lib.rs
- tests/version-numbers.rs
`html_root_url` is no longer needed: https://github.com/rust-lang-nursery/api-guidelines/commit/5c457dfa5340fd3ba2ede0ca6d5896c48d1e7d49.
I have added an `Installation` section to `README.md`.
> Remove html_root_url

- Cargo.toml
- src/lib.rs
See https://rust-lang-nursery.github.io/api-guidelines/interoperability.html#generic-readerwriter-functions-take-r-read-and-w-write-by-value-c-rw-value.
> Take readers and writers by value

- README.md
To the credit of everybody involved, both benchmarks work unmodified. Also, bleach got a lot faster.
Fixes #84
> Use Bleach 2.0 and Ammonia 1.0 in the README benchmark

- src/lib.rs
Here's a basic implementation. I'm not completely sure how it should interact with the whitelist:
1. If a tag is in the blacklist that takes precedence, and the whitelist is ignored for that tag. (currently implemented)
2. If a tag is in both blacklist and whitelist then panic. (annoying to use with default options but explicit)
3. When a tag is added to the blacklist, it's automatically removed from the whitelist. (adds complexity and doesn't work well with `rm_clean_content_tags`, but is consistent)
Also I think defaulting to `clean_content_tags(["script", "style"])` is a good idea, but I know defaults are hard to change.
Closes #89
> Add clean_content_tags()

- src/lib.rs
Similar to #96, but with a critical difference that this is a preprocessing step, before relative URLs are resolved. This allows different relative URLs for images than links.
I've named it `url_filter_map`, after a similar iterator filter in std.
I've opted for storing callback directly rather than via trait, but this required a custom `Debug`, since `derive` couldn't skip the callback.
> Context-sensitive relative URL rewrite

- src/lib.rs
The `is_url_attr` function is used to decide whether elements need their
URLs filtered to comply users that want all links to remain on-origin.
This patch adds missing the attributes (`action` for `<form>`,
`formaction` for `<input>` and `<button>` and `ping` for `<a>`).
I have used the (non-normative) reference in the HTML spec to ensure
comprehensivenes:
https://html.spec.whatwg.org/multipage/indices.html#attributes-3
> Adding `action`, `formaction` and `ping` to `is_url_attr`

- .travis.yml
- CHANGELOG.md
- Cargo.toml
- README.md
* Recognize `action`, `formaction` and `ping` as [URL attributes](https://html.spec.whatwg.org/multipage/indices.html#attributes-3) for scheme and origin filtering
* Add [`Builder::url_filter_map`] which allows URLs, both relative and absolute, to be pre-filtered
[`Builder::url_filter_map`]: https://docs.rs/ammonia/1.1/ammonia/struct.Builder.html#method.url_filter_map
> Release 1.2

- README.md
This is pinned in travis.yml, so we should be able to
guarantee long-term support for that old compiler.
> Mention Rust 1.24.0 in README

- src/lib.rs
As the title says. This is to improve library interoperability and ergonomics so that this is possible `format!("sanitized: {}", ammonia::clean("<a onclick="evil()">link</a>"))` instead of `format!("sanitized: {}", ammonia::clean("<a onclick="evil()">link</a>").to_string())`
> Implement Display trait for Document

- src/lib.rs
See #100.
- The `rm_tag_attribute_values` doctest is particularly bad.
Let me know if anything catches your eye that should be changed! :)
> Add a way to specify approved values of attributes

- README.md
1. It was out of date
2. As long as we use bors it will always be green
> Remove build status indicator

- CHANGELOG.md
- Cargo.toml
- src/lib.rs
> Fix handling of deeply nested tags

- src/lib.rs
This is a joint work with @shekyan, intend to solve #126 
**Background**
`data-` prefix is commonly used (such as google doc, etc.) and html sanitizers sometimes want to keep these attributes to support these interactive web apps. Before this commit, ammonia can only do exact match based attribute whitelist, instead of rule-based or prefix-based filtering.
**Proposed solution**
Added "prefix" based whitelist for generic attributes.
Introduced three new functions for Builder:
```rust
pub fn generic_attribute_prefixes(&mut self, value: HashSet<&'a str>) -> &mut Self;
pub fn add_generic_attribute_prefixes<T: 'a + ?Sized + Borrow<str>, I: IntoIter<Item = &'a T>>(
&mut self,
it: I,
) -> &mut Self;
pub fn rm_generic_attribute_prefixes<'b, T: 'b + ?Sized + Borrow<str>, I: IntoIter<Item = &'b …
```
> feature: whitelist generic attribute prefix

- src/lib.rs
It's possible for `Url::parse("xxx") == Err(url::ParseError::RelativeUrlWithoutBase)` to evaluate to true,
but for the eventual `url.join("xxx")` to still fail with a parse erro, depending on what "xxx" actually is.
To detect this, we check that joining succeeds in addition to the normal checks for relative URLs.
This PR also runs "cargo fmt".
Fixes #136
> Make sure that relative URLs actually work when filtering

- CHANGELOG.md
- Cargo.toml
- src/lib.rs
Reported as security vulnerability via private email.
The issue happens if developers added to the list of allowed tags any
tag which is parsed in RCDATA state, PLAINTEXT state or RCDATA state,
that is:
* title
* textarea
* xmp
* iframe
* noembed
* noframes
* plaintext
* noscript
* style
* script
An example in the wild is Plume, that allows iframe.  So in next
examples I'll assume the following policy:
Builder::new()
.add_tags(&["iframe"])
In HTML namespace `<iframe>` is parsed specially; that is, its content is
treated as text. For instance, the following html:
<iframe><a>test
Is parsed into the following DOM tree:
iframe
└─ #text: <a>test
So iframe cannot have any children other than a text node.
The same is not true, though, in "foreign content"; that is, within
`<svg>` or `<math>` …
> Fix namespace switching bugs, release 3.1.2

- .github/workflows/main.yml
- README.md
- src/lib.rs
I mixed up FF with CR when reading an ASCII table. Bug reported via email.
> Fix a space bug in `clean_text`

- src/lib.rs
Hey there,
This pull request adds a new `empty` constructor. This was mentioned in [#75](https://github.com/rust-ammonia/ammonia/issues/75#issuecomment-339138994) but never implemented.
I need this so that I can obtain `&Builder` and not `&mut Builder` which is returned when modifying the tags with `tags()`.
I'm happy to add an additional test as well if you like but the doctest seemed sufficient to me.
What do you think about this change? Thanks.
> Add empty() constructor

- CHANGELOG.md
- Cargo.toml
- src/lib.rs
This includes switching from the now-outdated lazy_static macro
to once_cell, which works without macros.
> Bump version to 3.2.0

- src/lib.rs
- src/rcdom.rs
This PR avoids fixing one clippy warning, since it's actually a breaking change.
```text
error: type `Document` implements inherent method `to_string(&self) -> String` which shadows the implementation of `Display`
--> src/lib.rs:2670:5
|
2670 | /     pub fn to_string(&self) -> String {
2671 | |         let opts = Self::serialize_opts();
2672 | |         let mut ret_val = Vec::new();
2673 | |         let inner: SerializableHandle = self.0.document.children.borrow()[0].clone().into();
...    |
2676 | |         String::from_utf8(ret_val).expect("html5ever only supports UTF8")
2677 | |     }
| |_____^
|
= note: `#[deny(clippy::inherent_to_string_shadow_display)]` on by default
= help: remove the inherent method from type `Document`
= help: for further information visit …
```
> Fix clippy warnings

- src/lib.rs
Fixes #175
With this patch, `UrlRelative` knows the outer lifetime `'a` and is bound by it.
I confirmed that the following code works.
```rust
use ammonia::*;
use std::borrow::Cow;
struct Eval<'a>(&'a str);
impl<'a> UrlRelativeEvaluate<'a> for Eval<'a> {
fn evaluate<'u>(&self, url: &'u str) -> Option<Cow<'u, str>> {
let mut s = self.0.to_string();
s.push_str(url);
Some(Cow::Owned(s))
}
}
fn main() {
let prefix = "/prefix/".to_string();
let eval = Eval(&prefix);
let mut sanitizer = Builder::default();
sanitizer.url_relative(UrlRelative::Custom(Box::new(eval)));
let s = "<a href=\"foo\">link</a>".to_string();
let s = sanitizer.clean(&s).to_string();
println!("{}", s)
}
```
Output:
```
> cargo run
Blocking waiting for file lock on build directory
Compiling ammonia v3.3.0 …
```
> Do not require `'static` to `UrlRelativeEvaluate`

- Cargo.toml
- src/lib.rs
- src/style.rs
Matches what I understand of Bleach's `CSSSanitizer`: CSS properties are filtered by name and global.
A few notes:
- Although CSS sanitization is not enabled by default (since mozilla/bleach#633), Bleach [provides a default set of properties](https://github.com/mozilla/bleach/blob/fcbe8f7fb144f3e65cbf00a464433558c80badec/bleach/css_sanitizer.py#L4-L53), maybe this should do the same?
- Much like bleach, when filtering is enabled the declarations will be "normalised" even if accepted as part of processing the declarations-list, for the most part this consists of removing malformed declarations as well as constructs which currently make no sense at the declaration level (e.g. at-rules are allowed by the grammar but there is currently no valid declaration-level at-rule, so they will be …
> Add support for sanitizing (filtering) style properties
