rust-ammonia/ammonia

- src/lib.rs
> Add support for relative URLs.

- src/lib.rs
> Add an option to keep elements that had attributes removed

- Cargo.toml
This updates serde from 0.9 to 1.0
> Bump html5ever to 0.18 and bump version

- src/lib.rs
> Add rel="noopener noreferrer" to links

- src/lib.rs
See https://github.com/rust-lang/crates.io/issues/974
> Provide a way to rewrite relative URLs with a chosen base URL

- src/lib.rs
> Add an `allowed_classes` parameter to ammonia

- CHANGELOG.md
- Cargo.toml
- src/lib.rs
> Fix a bug in the traversal code

- Cargo.toml
- src/lib.rs
> Set html_root_url (C-HTML-ROOT)

- src/lib.rs
> Add a constructor (C-CTOR)

- src/lib.rs
See C-COMMON-TRAITS, C-DEBUG and C-DEBUG-NONEMPTY.
Part of #31
> Implement common traits for Ammonia

- CHANGELOG.md
- README.md
Also add an "Unreleased" changelog entry.
Part of #31
> Link to the CHANGELOG (C-RELNOTES)

- src/lib.rs
> Require `Ammonia` to implement `Send` and `Sync`

- src/lib.rs
Errors are not handling yet. We can change those when we decide what to
do for the rest of the code.
Fixes #38
Do we also want to do something like this for the output?
> Allow passing in the HTML with a reader

- CHANGELOG.md
- src/lib.rs
Add a builder API.
Includes some minor documentation improvements.
Part of #31
> Builder pattern

- src/lib.rs
> Add examples

- .travis.yml
- CHANGELOG.md
- src/lib.rs
> Allow writing the output to a stream

- CHANGELOG.md
- src/lib.rs
> Document (and tweak) panic behavior

- src/lib.rs
Part of #31: C-LINK
Fixes #31, since C-LINK is the last open checkmark on that mega-issue.
> Add relevant hyperlinks to the documentation

- Cargo.toml
- src/lib.rs
> Add the custom UrlRelative policy

- src/lib.rs
> Add more getters and setters

- CHANGELOG.md
- Cargo.toml
- README.md
- src/lib.rs
Changes since RC2:
* Do not run the custom URL resolver on absolute URLs
* Update to html5ever 0.21
> Release 1.0.0-RC3

- CHANGELOG.md
- Cargo.toml
- README.md
- RELEASE_PROCESS.md
> Release 1.1.0

- src/lib.rs
> Use Borrow and IntoIter to allow slices to be directly added and removed

- CHANGELOG.md
- Cargo.toml
- examples/ammonia-cat.rs
- src/lib.rs
> Release 2.1.2

- CHANGELOG.md
- Cargo.toml
- README.md
- benchmarks/Cargo.toml
- benchmarks/src/main.rs
- examples/ammonia-cat.rs
- src/lib.rs
- tests/version-numbers.rs
> Miscellanous 2018 edition changes

- .travis.yml
- CHANGELOG.md
- Cargo.toml
- README.md
- benchmarks/Cargo.toml
- benchmarks/src/main.rs
- examples/ammonia-cat.rs
- src/lib.rs
- tests/version-numbers.rs
* Add [`clean_text`] function.
* Updated to [rust-url 2.0].
[`clean_text`]: https://docs.rs/ammonia/3.0.0/ammonia/fn.clean_text.html
[rust-url 2.0]: https://docs.rs/url/2.0.0/url/
> Release 3.0

- .travis.yml
- README.md
- src/lib.rs
See #110.
Please let me know if I missed anything! Tests all passed, as I'm sure CI will show. :)
> feat: support adding attribute values to elements

- CHANGELOG.md
- Cargo.toml
> Release 3.1.0

- CHANGELOG.md
- Cargo.toml
Bumps dependencies and version number.
> Release 3.1.1

- .travis.yml
- README.md
- src/lib.rs
Having looked at the TokenSink example in #75, this seemed mostly straightfoward.
I found a couple of other nits along my way that I figured I might just pick up and do within this pull request, but I'm happy to drop them or turn them into individual PRs, if I must.
> Detect html (see #75)

- src/lib.rs
This is to match the standard - see https://html.spec.whatwg.org/#global-attributes:classes-2. Not a security vulnerability, as `allowed_values` used a `HashSet` (no option of providing a function such `.starts_with("lang-")`).
Rust explicitly documents that it uses WhatWG's definition of ASCII whitespace - https://doc.rust-lang.org/stable/std/primitive.char.html#method.is_ascii_whitespace.
> Split class attribute by ASCII whitespace

- .github/workflows/main.yml
- README.md
This aligns with parking_lot_core, an indirect dependency.
CC #157
> Bump MSRV to 1.49

- Cargo.toml
- src/lib.rs
- src/rcdom.rs
> Update html5ever, vendor rcdom

- src/lib.rs
This pull request fix issue https://github.com/rust-ammonia/ammonia/issues/169
> Fix invalid example in document

- CHANGELOG.md
- src/lib.rs
> Implement `UrlRelative::RewriteWithRoot`

- src/lib.rs
> Use the `Display` trait instead of an inherent `to_string` method
